Fix UI error due to invalid type (#39)
Since the patch introduces UI error:
TypeError: onChangeHandler.withArg is not a function

* Use useMemo for rootHandler instead of useCallback.

In order to follow react-hooks/exhaustive-deps eslint rule